### ISSUE TITLE
"GetDeploymentPathFromVsixManifest" task failed unexpectedly, cannot debug sample

### ISSUE THREAD

**Issue by tgriff** [Microsoft/VSSDK-Extensibility-Samples#116]
### Installed products
- Visual Studio: Enterprise 2017 15.5.3

### Description
Trying to debug the TypingSpeed sample results in the following error:
```
error MSB4018: The "GetDeploymentPathFromVsixManifest" task failed unexpectedly.
error MSB4018: System.ArgumentNullException: Value cannot be null.
error MSB4018: Parameter name: path1
error MSB4018:    at System.IO.Path.Combine(String path1, String path2)
error MSB4018:    at Microsoft.VsSDK.Build.Tasks.ExtensionManagerUtilities.GetSettingsManagerForDevenv(String rootSuffix)
error MSB4018:    at Microsoft.VsSDK.Build.Tasks.GetDeploymentPathFromVsixManifest.Execute()
error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

### Steps to recreate
1. Download the samples .zip file and extract the TypingSpeed sample.
2. Double-click the .sln file to open the solution.
3. Hit F5 to build and start debugging the sample extension.

### Current behavior
I get the error above and am unable to debug the sample extension.

### Expected behavior
It should launch the experimental VS instance with the sample extension installed and the debugger attached.

### Other Info
* The "Start external program" path under the Debug settings is "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.exe" which I am certain is correct.
* If I uncheck the "Deploy VSIX content to experimental instance for debugging" option under the VSIX settings then the build succeeds, but I am still unable to debug the sample.

**Comment by AlexEyler** [comment]
I can't reproduce this on my machine, but I have seen this happen out in the wild in cases where setup is out-of-sync with the installed Visual Studio instances. Have you tried repairing your installation of VS?

**Comment by ktrzeciaknubisa** [comment]
I had the same problem (although with "Menu_And_Commands" sample). Funny, that I can't reproduce it anymore... Things started to work since I rebuilded the sample while running VS 2017 as Administrator on Windows.

**Comment by osnjunior91** [comment]
I was having this error, after updating the dependencies of the project via Nuget, the error disappeared.

**Comment by NecromancerKing** [comment]
> I was having this error, after updating the dependencies of the project via Nuget, the error disappeared.

Thank you @osnjunior91 . This saved from the hectic error. Updating Nuget packages to latest solved the issue.
