### ISSUE TITLE
Could you provide a sample for resources localization?

### ISSUE THREAD

**Issue by vincedan** [Microsoft/VSSDK-Extensibility-Samples#129]
### Description
 I have read Localizing [Menu Commands](https://docs.microsoft.com/en-US/visualstudio/extensibility/localizing-menu-commands) 
about how to localize menu/command, 

### Steps to recreate
1. Create new VSIX project
2. Add CustomToolWindow based on VS template.
3. do each instructions based on [Menu Commands](https://docs.microsoft.com/en-US/visualstudio/extensibility/localizing-menu-commands) 

### Current behavior
project can be compiled,  but when debug/execute it, System.IO.IOException will be thrown,  "can't find resource toolwindow1control.xaml" 

### Expected behavior
please provide correct instructions in ms doc or samples ..

**Comment by grokys** [comment]
I've tried following the same instructions, doesn't work for me either. I get:

```
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id, UInt32 flags)
   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id, ProvideToolWindowAttribute tool)
   at Microsoft.VisualStudio.Shell.Package.FindToolWindow(Type toolWindowType, Int32 id, Boolean create, ProvideToolWindowAttribute tool)
   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Guid& toolWindowType, Int32 id)
   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsToolWindowFactory.CreateToolWindow(Guid& toolWindowType, UInt32 id)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConstructContent()
```
