### ISSUE TITLE
Does not build out of the box on vs2017

### ISSUE THREAD

**Issue by Meai1** [Microsoft/VSSDK-Extensibility-Samples#59]
### Installed products
- Visual Studio: [example Professional 2017]

### Description
After project upgrade/migration, I build the solution and get an error. I dont have any older Visual Studio versions installed. I have VS2017 installed on the D:\\vs2017
I tried upgrading the entire project to the 15.0 version of this dll but I get tons of other problems with that approach.

### Steps to recreate
1. Load solution in vs2017
2. Build solution

![2017-04-28 19_42_45-ooklanguage - microsoft visual studio](https://cloud.githubusercontent.com/assets/1112157/25540304/e7eaee52-2c4a-11e7-8946-1b7e936b7d81.png)

**Comment by justcla** [comment]
Sorry for the inconvenience. We are working on upgrading the samples.
Which sample are you most interested in running?

**Comment by Meai1** [comment]
The Ook integration sample. I did finally get it running now, after upgrading to .net 4.6 in various places, replacing the nuget packages all with 15.0, fixing something in the vsix manifest (prerequisites was missing?)
Everything seems to be working except for the intellisense. I dont get any intellisense popup. 
It colors the text just fine and the hover info also shows up, but no intellise. No indication for why there is a problem. 
Only error I see in the output is:
`System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.ItemsControl', AncestorLevel='1''. BindingExpression:Path=VerticalContentAlignment; DataItem=null; target element is 'ListBoxItem' (Name=''); target property is 'VerticalContentAlignment' (type 'VerticalAlignment')
`

**Comment by justcla** [comment]
Thanks. The samples are currently written for VS2015. Hence why the extension manifest in in VSIXv2 format. I'm working on upgrading the Ook sample now.

**Comment by justcla** [comment]
I have merged in an upgrade that builds and runs on both VS2015 and VS2017.
Please let me know if it works for you. Thanks.

**Comment by gojimmypi** [comment]
I just installed a freshly compiled Ook, and it claims `This extension is not installable on any currently installed products.`

![image](https://user-images.githubusercontent.com/13059545/56080679-d925a780-5db8-11e9-8af4-53a22bccc097.png)

![image](https://user-images.githubusercontent.com/13059545/56080683-eb074a80-5db8-11e9-8069-99fd67079cea.png)

```
1>------ Rebuild All started: Project: OokLanguage, Configuration: Debug Any CPU ------
1>  OokLanguage -> C:\workspace\VSSDK-Extensibility-Samples\Ook_Language_Integration\C#\bin\Debug\OokLanguage.dll
1>  OokLanguage -> C:\workspace\VSSDK-Extensibility-Samples\Ook_Language_Integration\C#\bin\Debug\OokLanguage.vsix
1>  Enabled always loading Extensions from LocalAppData
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```

```
4/13/2019 6:48:42 AM - Microsoft VSIX Installer
4/13/2019 6:48:42 AM - -------------------------------------------
4/13/2019 6:48:42 AM - Initializing Install...
4/13/2019 6:48:43 AM - Extension Details...
4/13/2019 6:48:43 AM - 	Identifier      : c729d6b2-f512-49ed-893d-a8f61f25db98
4/13/2019 6:48:43 AM - 	Name            : OokLanguage
4/13/2019 6:48:43 AM - 	Author          : Microsoft
4/13/2019 6:48:43 AM - 	Version         : 1.0
4/13/2019 6:48:43 AM - 	Description     : Sample classifier extension to the Visual Studio Editor. Implements the 'Ook' language
4/13/2019 6:48:43 AM - 	Locale          : en-US
4/13/2019 6:48:43 AM - 	MoreInfoURL     : 
4/13/2019 6:48:43 AM - 	InstalledByMSI  : False
4/13/2019 6:48:43 AM - 	SupportedFrameworkVersionRange : [4.5]
4/13/2019 6:48:43 AM - 
4/13/2019 6:48:43 AM - 	Supported Products : 
4/13/2019 6:48:43 AM - 		Microsoft.VisualStudio.Community
4/13/2019 6:48:43 AM - 			Version : [14.0,16.0)
4/13/2019 6:48:43 AM - 
4/13/2019 6:48:43 AM - 	References      : 
4/13/2019 6:48:43 AM - 
4/13/2019 6:48:43 AM - Searching for applicable products...
4/13/2019 6:48:52 AM - Found installed product - Global Location
4/13/2019 6:48:52 AM - Found installed product - AtmelStudio
4/13/2019 6:48:52 AM - Found installed product - ssms
4/13/2019 6:48:52 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```
